### ISSUE TITLE
Can't run the pygame client

### ISSUE THREAD

**Issue by ayushdiagarwal** [WorkShoft/dj-pygame-pong#1]
I followed your readme, and when I tried to execute `make runclient`, it gave me this error

`$ make runclient`
`python client/main.py`
`make: python: Command not found`
`make: *** [Makefile:2: runclient] Error 127`

I'm on Ubuntu 20.04 (Linux)

**Comment by WorkShoft** [comment]
What happens when you run` python3 client/main.py?`

**Comment by ayushdiagarwal** [comment]
The client works now but I received a pygame error now


```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "client/main.py", line 6, in <module>
    scenes = loader.load_scenes(screen)
  File "/mnt/2ADAC21CDAC1E463/Programming/Others/Github/dj-pygame-pong/client/loader.py", line 21, in load_scenes
    menu = Menu(screen)
  File "/mnt/2ADAC21CDAC1E463/Programming/Others/Github/dj-pygame-pong/client/menu.py", line 30, in __init__
    pygame.mixer.music.play(fade_ms=20000)
TypeError: 'fade_ms' is an invalid keyword argument for this function

```

**Comment by WorkShoft** [comment]
You are using Pygame 1.9.6, you will need the version on the requirements.txt file as that keyword was introduced in a newer version.

You should create a virtual environment and run pip install -r requirements.txt there before you run the project.

**Comment by ayushdiagarwal** [comment]
I already created a virtual environment and installed the modules as you mentioned it in the requirements.txt file. I don't think that's the problem

**Comment by WorkShoft** [comment]
What does `pip freeze` show?

**Comment by ayushdiagarwal** [comment]
Looks like it was my fault. When I opened a new terminal it removed the virtual environment (env) from there. The game started but there was only one window, I thought I should run another client I did the same but I can't get the controls of the game.
It would be helpful if you can list the controls of the game.

Also, I am wondering how you connected the pygame window using Django channels because I thought you can only use Django for the web. Also, I'm wondering if Django is the way to connect the clients shouldn't something like the sockets module should be a better choice than Django? I'm curious about how you did this so please update the README with some explanation.

**Comment by WorkShoft** [comment]
Glad to know it worked - let me know if you run into any more issues.

I'm definitely going to spend some time documenting it, maybe I will write a blog post on fullstackdjango.com as well.
